import 'package:GitSync/constant/langLog.dart';
import 'package:re_highlight/languages/dart.dart';
import 'package:re_highlight/languages/javascript.dart';
import 'package:re_highlight/languages/typescript.dart';
import 'package:re_highlight/languages/json.dart';
import 'package:re_highlight/languages/python.dart';
import 'package:re_highlight/languages/java.dart';
import 'package:re_highlight/languages/cpp.dart';
import 'package:re_highlight/languages/csharp.dart';
import 'package:re_highlight/languages/go.dart';
import 'package:re_highlight/languages/ruby.dart';
import 'package:re_highlight/languages/php.dart';
import 'package:re_highlight/languages/xml.dart';
import 'package:re_highlight/languages/css.dart';
import 'package:re_highlight/languages/markdown.dart';
import 'package:re_highlight/languages/yaml.dart';
import 'package:re_highlight/languages/sql.dart';
import 'package:re_highlight/languages/bash.dart';
import 'package:re_highlight/languages/swift.dart';
import 'package:re_highlight/languages/kotlin.dart';
import 'package:re_highlight/languages/objectivec.dart';
import 'package:re_highlight/languages/scss.dart';
import 'package:re_highlight/languages/less.dart';
import 'package:re_highlight/languages/perl.dart';
import 'package:re_highlight/languages/rust.dart';
import 'package:re_highlight/languages/lua.dart';
import 'package:re_highlight/languages/shell.dart';
import 'package:re_highlight/languages/scala.dart';
import 'package:re_highlight/languages/haskell.dart';
import 'package:re_highlight/languages/clojure.dart';
import 'package:re_highlight/languages/elixir.dart';
import 'package:re_highlight/languages/erlang.dart';
import 'package:re_highlight/languages/powershell.dart';
import 'package:re_highlight/languages/makefile.dart';
import 'package:re_highlight/languages/prolog.dart';
import 'package:re_highlight/languages/r.dart';
import 'package:re_highlight/languages/tcl.dart';
import 'package:re_highlight/languages/vbnet.dart';
import 'package:re_highlight/languages/plaintext.dart';

final extensionToLanguageMap = {
  'dart': langDart,
  'js': langJavascript,
  'mjs': langJavascript,
  'ts': langTypescript,
  'json': langJson,
  'py': langPython,
  'java': langJava,
  'cpp': langCpp,
  'cc': langCpp,
  'cxx': langCpp,
  'cs': langCsharp,
  'go': langGo,
  'rb': langRuby,
  'php': langPhp,
  'html': langXml,
  'htm': langXml,
  'xml': langXml,
  'css': langCss,
  'md': langMarkdown,
  'markdown': langMarkdown,
  'yml': langYaml,
  'yaml': langYaml,
  'sql': langSql,
  'sh': langBash,
  'bash': langBash,
  'swift': langSwift,
  'kt': langKotlin,
  'kts': langKotlin,
  'm': langObjectivec,
  'mm': langObjectivec,
  'scss': langScss,
  'less': langLess,
  'pl': langPerl,
  'pm': langPerl,
  'rs': langRust,
  'lua': langLua,
  'zsh': langShell,
  'c': langCpp,
  'h': langCpp,
  'scala': langScala,
  'hs': langHaskell,
  'lhs': langHaskell,
  'clj': langClojure,
  'cljs': langClojure,
  'ex': langElixir,
  'exs': langElixir,
  'erl': langErlang,
  'ps1': langPowershell,
  'psm1': langPowershell,
  'makefile': langMakefile,
  'mk': langMakefile,
  'pro': langProlog,
  'log': langLog,
  'r': langR,
  'tcl': langTcl,
  'vb': langVbnet,
  'txt': langPlaintext,
};
