// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_log`, `commit`, `fast_forward`, `get_branch_name_priv`, `get_default_callbacks`, `get_uncommitted_file_paths_priv`, `set_author`

Future<void> init({String? homepath}) =>
    RustLib.instance.api.crateApiGitManagerInit(homepath: homepath);

Future<List<String>> getSubmodulePaths({required String pathString}) => RustLib
    .instance
    .api
    .crateApiGitManagerGetSubmodulePaths(pathString: pathString);

Future<void> cloneRepository({
  required String url,
  required String pathString,
  required String provider,
  required (String, String) credentials,
  required (String, String) author,
  required FutureOr<void> Function(String) cloneTaskCallback,
  required FutureOr<void> Function(int) cloneProgressCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCloneRepository(
  url: url,
  pathString: pathString,
  provider: provider,
  credentials: credentials,
  author: author,
  cloneTaskCallback: cloneTaskCallback,
  cloneProgressCallback: cloneProgressCallback,
  log: log,
);

Future<List<Commit>> getRecentCommits({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetRecentCommits(
  pathString: pathString,
  log: log,
);

Future<bool?> downloadChanges({
  required String pathString,
  required String remote,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  required FutureOr<void> Function() syncCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDownloadChanges(
  pathString: pathString,
  remote: remote,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  syncCallback: syncCallback,
  log: log,
);

Future<bool?> uploadChanges({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  required FutureOr<void> Function() syncCallback,
  required FutureOr<void> Function() mergeConflictCallback,
  List<String>? filePaths,
  required String syncMessage,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUploadChanges(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  syncCallback: syncCallback,
  mergeConflictCallback: mergeConflictCallback,
  filePaths: filePaths,
  syncMessage: syncMessage,
  log: log,
);

Future<void> forcePush({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  required String syncMessage,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerForcePush(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  syncMessage: syncMessage,
  log: log,
);

Future<void> forcePull({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  required (String, String) author,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerForcePull(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  author: author,
  log: log,
);

Future<void> discardChanges({
  required String pathString,
  required List<String> filePaths,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDiscardChanges(
  pathString: pathString,
  filePaths: filePaths,
  log: log,
);

Future<List<String>> getConflicting({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetConflicting(
  pathString: pathString,
  log: log,
);

Future<List<(String, int)>> getUncommittedFilePaths({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetUncommittedFilePaths(
  pathString: pathString,
  log: log,
);

Future<void> abortMerge({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerAbortMerge(
  pathString: pathString,
  log: log,
);

Future<(String, String)> generateSshKey({
  required String format,
  required String passphrase,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGenerateSshKey(
  format: format,
  passphrase: passphrase,
  log: log,
);

Future<String?> getBranchName({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetBranchName(
  pathString: pathString,
  log: log,
);

Future<List<String>> getBranchNames({
  required String pathString,
  required String remote,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetBranchNames(
  pathString: pathString,
  remote: remote,
  log: log,
);

Future<void> checkoutBranch({
  required String pathString,
  required String remote,
  required String branchName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCheckoutBranch(
  pathString: pathString,
  remote: remote,
  branchName: branchName,
  log: log,
);

Future<bool> getDisableSsl({required String gitDir}) =>
    RustLib.instance.api.crateApiGitManagerGetDisableSsl(gitDir: gitDir);

Future<void> setDisableSsl({required String gitDir, required bool disable}) =>
    RustLib.instance.api.crateApiGitManagerSetDisableSsl(
      gitDir: gitDir,
      disable: disable,
    );

Future<void> createBranch({
  required String pathString,
  required String newBranchName,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  required String sourceBranchName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCreateBranch(
  pathString: pathString,
  newBranchName: newBranchName,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  sourceBranchName: sourceBranchName,
  log: log,
);

class Commit {
  final PlatformInt64 timestamp;
  final String author;
  final String reference;
  final String commitMessage;
  final int additions;
  final int deletions;

  const Commit({
    required this.timestamp,
    required this.author,
    required this.reference,
    required this.commitMessage,
    required this.additions,
    required this.deletions,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      author.hashCode ^
      reference.hashCode ^
      commitMessage.hashCode ^
      additions.hashCode ^
      deletions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Commit &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          author == other.author &&
          reference == other.reference &&
          commitMessage == other.commitMessage &&
          additions == other.additions &&
          deletions == other.deletions;
}

enum LogType {
  global,
  accessibilityService,
  sync_,
  gitStatus,
  abortMerge,
  commit,
  getRepos,
  cloneRepo,
  selectDirectory,
  pullFromRepo,
  pushToRepo,
  forcePull,
  forcePush,
  recentCommits,
  syncException,
}
